### ISSUE TITLE
RuntimeError: wrapped C/C++ object of type QPushButton has been deleted

### ISSUE THREAD

**Issue by lang-learner** [ijgnd/anki21__editor_quick_note_and_deck_buttons#2]
First of all, thank you for this add-on.

Every once in a while I get the following error:

Caught exception:
Traceback (most recent call last):
  File "aqt\clayout.py", line 598, in accept
  File "aqt\clayout.py", line 609, in reject
  File "aqt\main.py", line 622, in reset
  File "aqt\gui_hooks.py", line 807, in __call__
  File "lib\site-packages\anki\hooks.py", line 451, in runHook
  File "aqt\modelchooser.py", line 47, in onReset
  File "aqt\modelchooser.py", line 93, in updateModels
RuntimeError: wrapped C/C++ object of type QPushButton has been deleted

Since I have no other add-on installed, is it possible that this add-on is causing it?

I'm on Windows 10 and I'm using Anki 2.1.20 (beta 5).
Thanks

**Comment by ijgnd** [comment]
Thanks for the report. I have the same problem with 2.1.20 beta5 with the version that is on ankiweb.

Anki 2.1.20 changed quite a few things that break many add-ons that I still need to look at. 

On my computer the problem seems to disappear when I adjust one line. Instead of verifying why this happens it's much easier to check if this also fixes it on your machine ...

Could you install [this file](https://github.com/ijgnd/anki21__editor_quick_note_and_deck_buttons/releases/download/2120_v1/anki21__editor_quick_note_and_deck_buttons__2020-01-26.ankiaddon), restart Anki and let me know if this fixes the problem for you. 

[Here](https://raw.githubusercontent.com/glutanimate/docs/master/anki/add-ons/media/ankiaddon-installation.gif) is a video that glutanimate made about installing ankiaddon files from outside of ankiweb. Naturally my name is different, but the principle applies. 

I don't use this add-on that much so I need other people's help.

**Comment by lang-learner** [comment]
After installing that file, the problem seems to be disappeared.

**Comment by ijgnd** [comment]
That's good news. If you run into this problem again let me know.
