### ISSUE TITLE
Add tags with specific buttons

### ISSUE THREAD

**Issue by Cupbox** [ijgnd/anki21__editor_quick_note_and_deck_buttons#5]
Similiar to #3
I use a single deck and use tags to organize my collection. 
My request is the ability to add say "#Language::English::Abbreviations" and switching to the English notetype on pressing an "Abbreviations" button

**Comment by ijgnd** [comment]
I made a new version that allows to switch the note type and deck at the same time and optionally add or remove tags and to focus to any field, for details check the config.md

If you are still interested it would be great if you could test this version which you can download from [here](https://github.com/ijgnd/anki21__editor_quick_note_and_deck_buttons/releases/download/untagged-6bfe0a8222ee48d266fc/anki21__editor_quick_note_and_deck_buttons__2020-04-16.ankiaddon).

Before you use this make sure to backup (copy and save) your custom config.

If it doesn't work just uninstall it and re-download the working version from github.

In theory add-ons can cause a lot of damage though at the moment I don't see how this new version could cause permanent problems since it only should work in the addcards window. Nevertheless I always add "Use this at your own risk".

If you find any bugs, have comments/feedback or ideas for improvement let me know here. I need some testing/feedback before I can upload this to ankiweb.

Thanks for your help.

**Comment by Cupbox** [comment]
Seems to be down for me. I assume you removed it?

**Comment by ijgnd** [comment]
I have no idea. Maybe our browsers behave differently?

When I click on "you can download from [here](https://github.com/ijgnd/anki21__editor_quick_note_and_deck_buttons/releases/download/untagged-6bfe0a8222ee48d266fc/anki21__editor_quick_note_and_deck_buttons__2020-04-16.ankiaddon)" my Firefox opens a save dialog for this file so that I can save it.

Instead of directly saving the file you usually view the github release page and then download "anki21__editor_quick_note_and_deck_buttons__2020-04-16.ankiaddon" from there. The [release page is here](https://github.com/ijgnd/anki21__editor_quick_note_and_deck_buttons/releases/tag/untagged-6bfe0a8222ee48d266fc).

Does this work?

**Comment by Cupbox** [comment]
I'm on FF too. Only release I can see is
![2020-04-16_18-18-12](https://user-images.githubusercontent.com/13769570/79460708-b7bb5500-7fe4-11ea-9736-57d90ce13974.png)

**Comment by ijgnd** [comment]
My mistake. Sorry. I only had a "draft" that's invisible to other users. I didn't know that this draft feature existed... Now it should work. Does it?

**Comment by ijgnd** [comment]
i think the urls changed, too.

the release page is at: https://github.com/ijgnd/anki21__editor_quick_note_and_deck_buttons/releases/

the direct link is at https://github.com/ijgnd/anki21__editor_quick_note_and_deck_buttons/releases/download/3/anki21__editor_quick_note_and_deck_buttons__2020-04-16.ankiaddon

**Comment by Cupbox** [comment]
Yup. Works. I'll check it out now.

**Comment by Cupbox** [comment]
Works perfectly for me ijgnd. Thanks alot!
"decknote type" in the config example was confusing for me. That's a typo, right?

**Comment by ijgnd** [comment]
thanks for pointing me to the typo. I have uploaded it in the meantime to ankiweb.

If you run into a problem with this new version please let me know and make a new topic.
